#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
export DOTFILES_DIR="${DOTFILES_DIR:-$script_dir}"

source "$DOTFILES_DIR/lib/utils.sh"

parse_args "$@"

log "Installing walker packages..."

set_context "Walker"

packages=(
	"walker"
)

install_packages_pacman "${packages[@]}"

elephant service enable
systemctl --user start elephant.service
