---
ansible_host: 192.168.1.216
# ansible_host: 192.168.1.242
boot_part_end: 1GB
swap_size: 1G
static_gateway: '192.168.1.1'
network_interface: 'enp0s3'
static_netmask: '24'
root_password: test
gpu_type: none # amd or nvidia or none
dual_boot: true
root_partition_size: 20GiB
install_drive: /dev/sda
free_space_end: true
