format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal\
$custom\
$sudo\
$cmd_duration\
$shell\
$line_break\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$character"""

## FIRST LINE/ROW: Info & Status
# First param ‚îÄ‚îå
[username]
format = " [‚ï≠‚îÄ$user]($style)@"
style_user = "bold red"
style_root = "bold red"
show_always = true

# Second param
[hostname]
format = "[$hostname]($style) in "
style = "bold dimmed red"
trim_at = "-"
ssh_only = false
disabled = false

# Third param
[directory]
style = "purple"
truncation_length = 0
truncate_to_repo = true
truncation_symbol = ""

[git_branch]
style = "green"

# Before all the version info (python, nodejs, php, etc.)
[git_status]
style = "white"
ahead = "‚á°${count}"
diverged = "‚áï‚á°${ahead_count}‚á£${behind_count}"
behind = "‚á£${count}"

# Last param in the first line/row
[cmd_duration]
min_time = 100
format = "took [$duration]($style) "
disabled = false

## SECOND LINE/ROW: Prompt
# Somethere at the beginning
[battery]
full_symbol = "Û∞Åπ "
charging_symbol = "Û∞ÇÑ "
discharging_symbol = "Û∞ÇÉ "
disabled = true

[[battery.display]]  # "bold red" style when capacity is between 0% and 10%
threshold = 15
style = "bold red"
disabled = true

[[battery.display]]  # "bold yellow" style when capacity is between 10% and 30%
threshold = 50
style = "bold yellow"
disabled = true

[[battery.display]]  # "bold green" style when capacity is between 10% and 30%
threshold = 80
style = "bold green"
disabled = true

# Prompt: optional param 1
[time]
format = " üïô $time($style)\n"
time_format = "%T"
style = "bright-white"
disabled = true

# Prompt: param 2 ‚îî‚îÄ
[character]
success_symbol = " [‚ï∞‚îÄŒª](bold red)"
error_symbol = " [‚ï∞‚îÄ√ó](bold red)"

[shell]
format = '[$indicator]($style) '
fish_indicator = 'Û∞à∫'
powershell_indicator = 'Ôë†_'
unknown_indicator = ''
style = 'cyan bold'
disabled = false 

