---
- name: Ensure GitHub SSH keys are added and system settings are configured
  hosts: all
  become: true
  tasks:
    - name: Ensure .ssh directory exists
      file:
        path: "{{ ansible_env.HOME }}/.ssh"
        state: directory
        mode: '0700'

    - name: Download GitHub SSH keys
      uri:
        url: "https://github.com/nick22985.keys"
        return_content: yes
      register: github_keys

    - name: Ensure authorized_keys file exists
      file:
        path: "{{ ansible_env.HOME }}/.ssh/authorized_keys"
        state: touch
        mode: '0600'

    - name: Add GitHub keys to authorized_keys if not already present
      lineinfile:
        path: "{{ ansible_env.HOME }}/.ssh/authorized_keys"
        line: "{{ item }}"
        state: present
      loop: "{{ github_keys.content.splitlines() }}"

    - name: Ensure max_user_watches is set in sysctl.conf
      sysctl:
        name: fs.inotify.max_user_watches
        value: '9999999'
        state: present
        sysctl_set: yes

    - name: Ensure max_queued_events is set in sysctl.conf
      sysctl:
        name: fs.inotify.max_queued_events
        value: '9999999'
        state: present
        sysctl_set: yes

