wallpaper {
    monitor = desc:Samsung Electric Company Odyssey G95NC HNTX400116
    path = ~/.config/hypr/wallpapers/wallpaper-1.jpeg
    fit_mode = cover
}

wallpaper {
    monitor = desc:LG Electronics LG ULTRAGEAR 107NTNH1W367
    path = ~/.config/hypr/wallpapers/wallpaper-2.webp
    fit_mode = cover
}

wallpaper {
    monitor = desc:LG Electronics LG ULTRAGEAR 106NTGYDZ367
    path = ~/.config/hypr/wallpapers/wallpaper-4.jpeg
    fit_mode = cover
}

wallpaper {
    monitor = desc:LG Electronics LG ULTRAGEAR 107NTQD1V116
    path = ~/.config/hypr/wallpapers/wallpaper-1.jpg
    fit_mode = cover
}
wallpaper {
    monitor =
    path = ~/.config/hypr/wallpapers/wallpaper.jpg
    fit_mode = cover
}


splash = 0
