# set shortcut windows
# "C:\Program Files\Alacritty\alacritty.exe" --config-file %userprofile%\.alacritty.toml

general.import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]
# for windows
# [shell]
# program = "pwsh"


[env]
TERM = "xterm-256color"


[window]
# opacity = 0.9

padding.x = 0
padding.y = 0

decorations = "full"
decorations_theme_variant = "Dark" # "Dark"
startup_mode = "Maximized"

[font]
normal.family = "MesloLgs Nerd Font"
bold.family = "MesloLgs Nerd Font"
italic.family = "MesloLgs Nerd Font"
bold_italic.family = "MesloLgs Nerd Font"

size = 12.0


[scrolling]
history = 100000

[terminal]
osc52 = "CopyPaste"

[keyboard]
bindings = [
  # { key = "V", mods = "Control", action = "Paste" },
  # { key = "C", mods = "Control", action = "Copy" },
  { key = "Slash", mods = "Control", chars = "\u001f" },
  { key = "Backslash", mods = "Control", chars = "\u001c" }, # broken
  { key = "1", mods = "Control", chars = "\u0031" },
  { key = "2", mods = "Control", chars = "\u0000" }, # broken
  { key = "3", mods = "Control", chars = "\u001b" },
  { key = "4", mods = "Control", chars = "\u001c" },
  { key = "5", mods = "Control", chars = "\u001d" },
  { key = "6", mods = "Control", chars = "\u001e" },
  { key = "7", mods = "Control", chars = "\u001f" },
  { key = "8", mods = "Control", chars = "\u007F" },
  { key = "9", mods = "Control", chars = "\u0039" },
  { key = "0", mods = "Control", chars = "\u0000" }, # broken
]

[cursor]
style = { shape = "Beam", blinking = "On" }
 

